steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/quests-michael/demo-app', '.']
images:
- 'gcr.io/quests-michael/demo-app'

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/quests-michael/demo-app', '.']

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/quests-michael/demo-app']

  # Set up kubectl
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials autopilot-cluster-1 --zone europe-west1 --project quests-michael
        kubectl set image deployment/my-app-deployment CONTAINER_NAME=gcr.io/quests-michael/demo-app:latest

images:
  - 'gcr.io/quests-michael/demo-app'

