apiVersion: apps/v1
kind: Deployment
metadata:
 name: demo-deployment
spec:
 replicas: 1
 selector:
   matchLabels:
     app: demo
 template:
   metadata:
     labels:
       app: demo
   spec:
     containers:
     - name: demo-container
       image: europe-west3-docker.pkg.dev/quests-michael/demo-app/demo-image:v1
       command: ["python", "app.py"]
       ports:
       - containerPort: 80
